language: node_js
node_js:
  - "14"
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn install
  - yarn test:lib --silent --coverage
  - bash <(curl -s https://codecov.io/bash) -f packages/lib/coverage/coverage-final.json

before_deploy: yarn global add vercel # Install Vercel CLI on Travis
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: yarn deploy:vercel
    skip_cleanup: true
    on:
      branch: master
